### PR TITLE
fix: fixed problem when seriesTracks contains also cars

### LINKED ISSUE #5: Site fails to load after enabling Participation Credit Program toggle
After I enable the new "Show participation credit program" toggle from #4, the site just loads a blank page.

I can't replicate this on a fresh instance, so here is my export URL: https://adrianulima.github.io/my-racing-planner/?myCars=10518-10497-10473&myTracks=10574-10340-10132-10317-10547-10228-10299-10498-10511-10107-10349-10355-10395-10396-0-10506-10025-10082-10536-10042-10027-10282-10060-10557&wishCars=&wishTracks=&favoriteSeries=571-139-514-491-502-112-541-540-542-498-455-526-182

This is the error I see in the console: 
`Cannot read properties of undefined (reading 'free')
    at season-page-DOMEbIhz.js:5:40252`

Image

### PR DESCRIPTION
**Pull request by raikwallace**
In this case the problem was "Ring Meister by Ricmotech" serie. It seems that the same list is used for tracks and cars, so it was necessary to filter them out.

This should fix #5

### CODE REVIEW

File: src/components/season/season-table-header-participation.tsx [hunk 1]
```diff
@@ -9,9 +9,14 @@ import { Tooltip } from "../ui/tooltip";
 function SeasonTableHeaderParticipation({
   seriesTracks,
 }: {
-  seriesTracks: { [key: number]: number };
+  seriesTracks: { [key: string]: number };
 }) {
   const { myTracks } = useIr();
+  Object.keys(seriesTracks).forEach((key) => {
```
Comment (adrianulima) [inline src/components/season/season-table-header-participation.tsx:15]: In React we can't mutate the values coming from the props, so in this case you need to create a copy object like:

```ts
const filteredTracks = Object.fromEntries(
  Object.entries(seriesTracks).filter(([key]) => !key.includes("_cars"))
);

const tracks = Object.values(filteredTracks).map(
  (trackId) => TRACKS_JSON[trackId.toString() as keyof typeof TRACKS_JSON]
);
```

File: src/components/season/season-table-header-participation.tsx [hunk 2]
```diff
@@ -36,9 +41,8 @@ function SeasonTableHeaderParticipation({
     <Tooltip
       lazyMount
       unmountOnExit
-      content={`Participation credit program: ${
-        enoughTracks ? "Yes" : "No"
-      } (${numberOfTracks}/${tracksNeeded})`}
+      content={`Participation credit program: ${enoughTracks ? "Yes" : "No"
```
Comment (adrianulima) [inline src/components/season/season-table-header-participation.tsx:44]: I think you don't have ESLint and Prettier extensions configured in your IDE 🤔 Or they're not following the lint rules configured.
I think this line is not formatted correctly.

**Review by adrianulima — CHANGES_REQUESTED** [review]

**Comment by adrianulima** [comment]
@raikwallace For some reason my github stopped notifying me about new issues and PRs, I'll check that. Since this was a bug I fixed and made a deploy already.
Thanks for fixing it, I still left a few comments for you about React and linting.

File: src/components/season/season-table-header-participation.tsx (hunk 2 above)
Comment (raikwallace) [reply src/components/season/season-table-header-participation.tsx]: This is weird, I just ensured I applied the linter before merge and it made this challenge. I will check if it's picking the config from another place. Sorry!

File: src/components/season/season-table-header-participation.tsx (hunk 1 above)
Comment (raikwallace) [reply src/components/season/season-table-header-participation.tsx]: Noted! I'll try to apply this from now on. Thanks for the head up!

**Comment by raikwallace** [comment]
Thanks for the comments @adrianulima, they will help me in the future!

File: src/components/season/season-table-header-participation.tsx (hunk 2 above)
Comment (raikwallace) [reply src/components/season/season-table-header-participation.tsx]: Hi @adrianulima , I was trying to figure out what was wrong with my config, but I saw that maybe the eslint config file and the version used in the project are not compatible. Maybe the problem comes from that.
```
❯ pnpm lint

> my-racing@0.7.7 lint /.../my-racing-planner
> eslint .


Oops! Something went wrong! :(

ESLint: 9.17.0

ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:

https://eslint.org/docs/latest/use/configure/migration-guide

If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.

 ELIFECYCLE  Command failed with exit code 2.
```
That is the result I get when I try to run `pnpm lint`.
Should we try to migrate the config?

Comment (adrianulima) [reply src/components/season/season-table-header-participation.tsx]: Oh, it seems the `.eslintrc` file is not supported anymore. I tried running the migration but now it is complainig about other stuff.
I was already thinking on using `Biome` as replacement to ESLint and Prettier, I think this is a good time for that 🤔 

I'll make this change later today, thanks for pointing that error!
